export const GITHUB_PUBLIC_DATA_FIELDS = [
  { id: 1, category: "Identity", field: "user.id", description: "GitHub internal numeric user id" },
  { id: 2, category: "Identity", field: "user.node_id", description: "Graph node identifier" },
  { id: 3, category: "Identity", field: "user.login", description: "Username/login handle" },
  { id: 4, category: "Identity", field: "user.name", description: "Public full name" },
  { id: 5, category: "Identity", field: "user.avatar_url", description: "Profile avatar image URL" },
  { id: 6, category: "Identity", field: "user.gravatar_id", description: "Legacy gravatar identifier" },
  { id: 7, category: "Identity", field: "user.url", description: "API URL for user" },
  { id: 8, category: "Identity", field: "user.html_url", description: "Public profile URL" },
  { id: 9, category: "Identity", field: "user.type", description: "Account type (User/Organization)" },
  { id: 10, category: "Identity", field: "user.site_admin", description: "GitHub staff/admin flag" },
  { id: 11, category: "Identity", field: "user.bio", description: "Public biography" },
  { id: 12, category: "Identity", field: "user.company", description: "Public company value" },
  { id: 13, category: "Identity", field: "user.blog", description: "Website/blog URL" },
  { id: 14, category: "Identity", field: "user.location", description: "Public location" },
  { id: 15, category: "Identity", field: "user.hireable", description: "Hireable flag if shared" },
  { id: 16, category: "Identity", field: "user.email", description: "Public email if explicitly public" },
  { id: 17, category: "Identity", field: "user.twitter_username", description: "Linked X/Twitter username" },
  { id: 18, category: "Identity", field: "user.created_at", description: "Account creation timestamp" },
  { id: 19, category: "Identity", field: "user.updated_at", description: "Last profile update timestamp" },
  { id: 20, category: "Identity", field: "user.plan", description: "Plan details when available in API context" },

  { id: 21, category: "Social", field: "user.followers", description: "Followers count" },
  { id: 22, category: "Social", field: "user.following", description: "Following count" },
  { id: 23, category: "Social", field: "user.followers_url", description: "Followers endpoint URL" },
  { id: 24, category: "Social", field: "user.following_url", description: "Following endpoint URL" },
  { id: 25, category: "Social", field: "user.gists_url", description: "Gist endpoint URL" },
  { id: 26, category: "Social", field: "user.starred_url", description: "Starred repos endpoint URL" },
  { id: 27, category: "Social", field: "user.subscriptions_url", description: "Watch/subscriptions endpoint URL" },
  { id: 28, category: "Social", field: "user.organizations_url", description: "Public org memberships endpoint" },
  { id: 29, category: "Social", field: "user.events_url", description: "Public user events endpoint" },
  { id: 30, category: "Social", field: "user.received_events_url", description: "Received events endpoint" },

  { id: 31, category: "Repositories", field: "user.public_repos", description: "Total public repositories" },
  { id: 32, category: "Repositories", field: "user.public_gists", description: "Total public gists" },
  { id: 33, category: "Repositories", field: "repo.id", description: "Repository id" },
  { id: 34, category: "Repositories", field: "repo.node_id", description: "Repository graph node id" },
  { id: 35, category: "Repositories", field: "repo.name", description: "Repository short name" },
  { id: 36, category: "Repositories", field: "repo.full_name", description: "owner/name full repo name" },
  { id: 37, category: "Repositories", field: "repo.private", description: "Visibility flag (false for public repos)" },
  { id: 38, category: "Repositories", field: "repo.owner", description: "Owner object metadata" },
  { id: 39, category: "Repositories", field: "repo.html_url", description: "Repository web URL" },
  { id: 40, category: "Repositories", field: "repo.description", description: "Repository description" },
  { id: 41, category: "Repositories", field: "repo.fork", description: "Whether repository is a fork" },
  { id: 42, category: "Repositories", field: "repo.url", description: "Repository API URL" },
  { id: 43, category: "Repositories", field: "repo.branches_url", description: "Branches endpoint template" },
  { id: 44, category: "Repositories", field: "repo.tags_url", description: "Tags endpoint" },
  { id: 45, category: "Repositories", field: "repo.languages_url", description: "Language breakdown endpoint" },
  { id: 46, category: "Repositories", field: "repo.stargazers_url", description: "Stargazers endpoint" },
  { id: 47, category: "Repositories", field: "repo.contributors_url", description: "Contributors endpoint" },
  { id: 48, category: "Repositories", field: "repo.subscribers_url", description: "Watchers/subscribers endpoint" },
  { id: 49, category: "Repositories", field: "repo.commits_url", description: "Commits endpoint template" },
  { id: 50, category: "Repositories", field: "repo.releases_url", description: "Releases endpoint template" },
  { id: 51, category: "Repositories", field: "repo.deployments_url", description: "Deployments endpoint" },
  { id: 52, category: "Repositories", field: "repo.created_at", description: "Repository creation timestamp" },
  { id: 53, category: "Repositories", field: "repo.updated_at", description: "Repository last update timestamp" },
  { id: 54, category: "Repositories", field: "repo.pushed_at", description: "Latest push timestamp" },
  { id: 55, category: "Repositories", field: "repo.git_url", description: "Git protocol clone URL" },

  { id: 56, category: "Repository Metrics", field: "repo.ssh_url", description: "SSH clone URL" },
  { id: 57, category: "Repository Metrics", field: "repo.clone_url", description: "HTTPS clone URL" },
  { id: 58, category: "Repository Metrics", field: "repo.svn_url", description: "SVN URL" },
  { id: 59, category: "Repository Metrics", field: "repo.homepage", description: "Configured project homepage" },
  { id: 60, category: "Repository Metrics", field: "repo.size", description: "Repository size metric" },
  { id: 61, category: "Repository Metrics", field: "repo.stargazers_count", description: "Stars count" },
  { id: 62, category: "Repository Metrics", field: "repo.watchers_count", description: "Watchers count" },
  { id: 63, category: "Repository Metrics", field: "repo.language", description: "Primary language" },
  { id: 64, category: "Repository Metrics", field: "repo.has_issues", description: "Issues enabled flag" },
  { id: 65, category: "Repository Metrics", field: "repo.has_projects", description: "Projects enabled flag" },
  { id: 66, category: "Repository Metrics", field: "repo.has_downloads", description: "Downloads enabled flag" },
  { id: 67, category: "Repository Metrics", field: "repo.has_wiki", description: "Wiki enabled flag" },
  { id: 68, category: "Repository Metrics", field: "repo.has_pages", description: "Pages enabled flag" },
  { id: 69, category: "Repository Metrics", field: "repo.has_discussions", description: "Discussions enabled flag" },
  { id: 70, category: "Repository Metrics", field: "repo.forks_count", description: "Forks count" },

  { id: 71, category: "Repository Metrics", field: "repo.mirror_url", description: "Mirror URL when mirrored" },
  { id: 72, category: "Repository Metrics", field: "repo.archived", description: "Archived flag" },
  { id: 73, category: "Repository Metrics", field: "repo.disabled", description: "Disabled flag" },
  { id: 74, category: "Repository Metrics", field: "repo.open_issues_count", description: "Open issues total" },
  { id: 75, category: "Repository Metrics", field: "repo.license", description: "License metadata" },
  { id: 76, category: "Repository Metrics", field: "repo.allow_forking", description: "Allow forking policy" },
  { id: 77, category: "Repository Metrics", field: "repo.is_template", description: "Template repository flag" },
  { id: 78, category: "Repository Metrics", field: "repo.web_commit_signoff_required", description: "Web signoff requirement" },
  { id: 79, category: "Repository Metrics", field: "repo.topics", description: "Repository topics array" },
  { id: 80, category: "Repository Metrics", field: "repo.visibility", description: "Visibility type string" },

  { id: 81, category: "Code & Activity", field: "repo.default_branch", description: "Default branch name" },
  { id: 82, category: "Code & Activity", field: "repo.network_count", description: "Network count value" },
  { id: 83, category: "Code & Activity", field: "repo.subscribers_count", description: "Subscribers count" },
  { id: 84, category: "Code & Activity", field: "commit.sha", description: "Commit SHA hashes" },
  { id: 85, category: "Code & Activity", field: "commit.commit.message", description: "Commit messages" },
  { id: 86, category: "Code & Activity", field: "commit.commit.author", description: "Commit author metadata" },
  { id: 87, category: "Code & Activity", field: "commit.commit.committer", description: "Committer metadata" },
  { id: 88, category: "Code & Activity", field: "commit.stats", description: "Additions/deletions/total stats" },
  { id: 89, category: "Code & Activity", field: "commit.files", description: "Changed file list and patches" },
  { id: 90, category: "Code & Activity", field: "events.type", description: "Public event type stream" },

  { id: 91, category: "Collaboration", field: "pull_request.number", description: "PR number metadata" },
  { id: 92, category: "Collaboration", field: "pull_request.state", description: "PR open/closed/merged state" },
  { id: 93, category: "Collaboration", field: "pull_request.merged_at", description: "Merge timestamp" },
  { id: 94, category: "Collaboration", field: "pull_request.changed_files", description: "Changed file count in PR" },
  { id: 95, category: "Collaboration", field: "pull_request.additions", description: "Total additions in PR" },
  { id: 96, category: "Collaboration", field: "pull_request.deletions", description: "Total deletions in PR" },
  { id: 97, category: "Collaboration", field: "issue.number", description: "Issue number metadata" },
  { id: 98, category: "Collaboration", field: "issue.state", description: "Issue state and lifecycle" },
  { id: 99, category: "Collaboration", field: "issue.comments", description: "Issue comment count/details" },
  { id: 100, category: "Collaboration", field: "gist.files", description: "Public gist files and metadata" },
];

export const GITHUB_CATEGORY_COLORS = {
  Identity: "bg-violet-500",
  Social: "bg-indigo-500",
  Repositories: "bg-blue-500",
  "Repository Metrics": "bg-cyan-500",
  "Code & Activity": "bg-emerald-500",
  Collaboration: "bg-fuchsia-500",
};
